// GENERATED FILE - do not edit by hand.
//
// Built from ICU region names (Intl.DisplayNames) intersected with the flag
// assets bundled in the country_flags package, so every entry is guaranteed to
// render a flag rather than an empty box. 258 countries and
// territories, sorted by English name.
//
// Regenerate with: node scratchpad/gen_countries.js

import 'country.dart';

const List<Country> kCountries = [
  Country('AF', 'Afghanistan'),
  Country('AX', 'Åland Islands'),
  Country('AL', 'Albania'),
  Country('DZ', 'Algeria'),
  Country('AS', 'American Samoa'),
  Country('AD', 'Andorra'),
  Country('AO', 'Angola'),
  Country('AI', 'Anguilla'),
  Country('AQ', 'Antarctica'),
  Country('AG', 'Antigua & Barbuda'),
  Country('AR', 'Argentina'),
  Country('AM', 'Armenia'),
  Country('AW', 'Aruba'),
  Country('AC', 'Ascension Island'),
  Country('AU', 'Australia'),
  Country('AT', 'Austria'),
  Country('AZ', 'Azerbaijan'),
  Country('BS', 'Bahamas'),
  Country('BH', 'Bahrain'),
  Country('BD', 'Bangladesh'),
  Country('BB', 'Barbados'),
  Country('BY', 'Belarus'),
  Country('BE', 'Belgium'),
  Country('BZ', 'Belize'),
  Country('BJ', 'Benin'),
  Country('BM', 'Bermuda'),
  Country('BT', 'Bhutan'),
  Country('BO', 'Bolivia'),
  Country('BA', 'Bosnia & Herzegovina'),
  Country('BW', 'Botswana'),
  Country('BV', 'Bouvet Island'),
  Country('BR', 'Brazil'),
  Country('IO', 'British Indian Ocean Territory'),
  Country('VG', 'British Virgin Islands'),
  Country('BN', 'Brunei'),
  Country('BG', 'Bulgaria'),
  Country('BF', 'Burkina Faso'),
  Country('BI', 'Burundi'),
  Country('KH', 'Cambodia'),
  Country('CM', 'Cameroon'),
  Country('CA', 'Canada'),
  Country('IC', 'Canary Islands'),
  Country('CV', 'Cape Verde'),
  Country('BQ', 'Caribbean Netherlands'),
  Country('KY', 'Cayman Islands'),
  Country('CF', 'Central African Republic'),
  Country('EA', 'Ceuta & Melilla'),
  Country('TD', 'Chad'),
  Country('CL', 'Chile'),
  Country('CN', 'China'),
  Country('CX', 'Christmas Island'),
  Country('CP', 'Clipperton Island'),
  Country('CC', 'Cocos (Keeling) Islands'),
  Country('CO', 'Colombia'),
  Country('KM', 'Comoros'),
  Country('CG', 'Congo - Brazzaville'),
  Country('CD', 'Congo - Kinshasa'),
  Country('CK', 'Cook Islands'),
  Country('CR', 'Costa Rica'),
  Country('CI', 'Côte d’Ivoire'),
  Country('HR', 'Croatia'),
  Country('CU', 'Cuba'),
  Country('CW', 'Curaçao'),
  Country('CY', 'Cyprus'),
  Country('CZ', 'Czechia'),
  Country('DK', 'Denmark'),
  Country('DG', 'Diego Garcia'),
  Country('DJ', 'Djibouti'),
  Country('DM', 'Dominica'),
  Country('DO', 'Dominican Republic'),
  Country('EC', 'Ecuador'),
  Country('EG', 'Egypt'),
  Country('SV', 'El Salvador'),
  Country('GQ', 'Equatorial Guinea'),
  Country('ER', 'Eritrea'),
  Country('EE', 'Estonia'),
  Country('SZ', 'Eswatini'),
  Country('ET', 'Ethiopia'),
  Country('EU', 'European Union'),
  Country('FK', 'Falkland Islands'),
  Country('FO', 'Faroe Islands'),
  Country('FJ', 'Fiji'),
  Country('FI', 'Finland'),
  Country('FR', 'France'),
  Country('GF', 'French Guiana'),
  Country('PF', 'French Polynesia'),
  Country('TF', 'French Southern Territories'),
  Country('GA', 'Gabon'),
  Country('GM', 'Gambia'),
  Country('GE', 'Georgia'),
  Country('DE', 'Germany'),
  Country('GH', 'Ghana'),
  Country('GI', 'Gibraltar'),
  Country('GR', 'Greece'),
  Country('GL', 'Greenland'),
  Country('GD', 'Grenada'),
  Country('GP', 'Guadeloupe'),
  Country('GU', 'Guam'),
  Country('GT', 'Guatemala'),
  Country('GG', 'Guernsey'),
  Country('GN', 'Guinea'),
  Country('GW', 'Guinea-Bissau'),
  Country('GY', 'Guyana'),
  Country('HT', 'Haiti'),
  Country('HM', 'Heard & McDonald Islands'),
  Country('HN', 'Honduras'),
  Country('HK', 'Hong Kong SAR China'),
  Country('HU', 'Hungary'),
  Country('IS', 'Iceland'),
  Country('IN', 'India'),
  Country('ID', 'Indonesia'),
  Country('IR', 'Iran'),
  Country('IQ', 'Iraq'),
  Country('IE', 'Ireland'),
  Country('IM', 'Isle of Man'),
  Country('IL', 'Israel'),
  Country('IT', 'Italy'),
  Country('JM', 'Jamaica'),
  Country('JP', 'Japan'),
  Country('JE', 'Jersey'),
  Country('JO', 'Jordan'),
  Country('KZ', 'Kazakhstan'),
  Country('KE', 'Kenya'),
  Country('KI', 'Kiribati'),
  Country('XK', 'Kosovo'),
  Country('KW', 'Kuwait'),
  Country('KG', 'Kyrgyzstan'),
  Country('LA', 'Laos'),
  Country('LV', 'Latvia'),
  Country('LB', 'Lebanon'),
  Country('LS', 'Lesotho'),
  Country('LR', 'Liberia'),
  Country('LY', 'Libya'),
  Country('LI', 'Liechtenstein'),
  Country('LT', 'Lithuania'),
  Country('LU', 'Luxembourg'),
  Country('MO', 'Macao SAR China'),
  Country('MG', 'Madagascar'),
  Country('MW', 'Malawi'),
  Country('MY', 'Malaysia'),
  Country('MV', 'Maldives'),
  Country('ML', 'Mali'),
  Country('MT', 'Malta'),
  Country('MH', 'Marshall Islands'),
  Country('MQ', 'Martinique'),
  Country('MR', 'Mauritania'),
  Country('MU', 'Mauritius'),
  Country('YT', 'Mayotte'),
  Country('MX', 'Mexico'),
  Country('FM', 'Micronesia'),
  Country('MD', 'Moldova'),
  Country('MC', 'Monaco'),
  Country('MN', 'Mongolia'),
  Country('ME', 'Montenegro'),
  Country('MS', 'Montserrat'),
  Country('MA', 'Morocco'),
  Country('MZ', 'Mozambique'),
  Country('MM', 'Myanmar (Burma)'),
  Country('NA', 'Namibia'),
  Country('NR', 'Nauru'),
  Country('NP', 'Nepal'),
  Country('NL', 'Netherlands'),
  Country('NC', 'New Caledonia'),
  Country('NZ', 'New Zealand'),
  Country('NI', 'Nicaragua'),
  Country('NE', 'Niger'),
  Country('NG', 'Nigeria'),
  Country('NU', 'Niue'),
  Country('NF', 'Norfolk Island'),
  Country('KP', 'North Korea'),
  Country('MK', 'North Macedonia'),
  Country('MP', 'Northern Mariana Islands'),
  Country('NO', 'Norway'),
  Country('OM', 'Oman'),
  Country('PK', 'Pakistan'),
  Country('PW', 'Palau'),
  Country('PS', 'Palestinian Territories'),
  Country('PA', 'Panama'),
  Country('PG', 'Papua New Guinea'),
  Country('PY', 'Paraguay'),
  Country('PE', 'Peru'),
  Country('PH', 'Philippines'),
  Country('PN', 'Pitcairn Islands'),
  Country('PL', 'Poland'),
  Country('PT', 'Portugal'),
  Country('PR', 'Puerto Rico'),
  Country('QA', 'Qatar'),
  Country('RE', 'Réunion'),
  Country('RO', 'Romania'),
  Country('RU', 'Russia'),
  Country('RW', 'Rwanda'),
  Country('WS', 'Samoa'),
  Country('SM', 'San Marino'),
  Country('ST', 'São Tomé & Príncipe'),
  Country('SA', 'Saudi Arabia'),
  Country('SN', 'Senegal'),
  Country('RS', 'Serbia'),
  Country('SC', 'Seychelles'),
  Country('SL', 'Sierra Leone'),
  Country('SG', 'Singapore'),
  Country('SX', 'Sint Maarten'),
  Country('SK', 'Slovakia'),
  Country('SI', 'Slovenia'),
  Country('SB', 'Solomon Islands'),
  Country('SO', 'Somalia'),
  Country('ZA', 'South Africa'),
  Country('GS', 'South Georgia & South Sandwich Islands'),
  Country('KR', 'South Korea'),
  Country('SS', 'South Sudan'),
  Country('ES', 'Spain'),
  Country('LK', 'Sri Lanka'),
  Country('BL', 'St. Barthélemy'),
  Country('SH', 'St. Helena'),
  Country('KN', 'St. Kitts & Nevis'),
  Country('LC', 'St. Lucia'),
  Country('MF', 'St. Martin'),
  Country('PM', 'St. Pierre & Miquelon'),
  Country('VC', 'St. Vincent & Grenadines'),
  Country('SD', 'Sudan'),
  Country('SR', 'Suriname'),
  Country('SJ', 'Svalbard & Jan Mayen'),
  Country('SE', 'Sweden'),
  Country('CH', 'Switzerland'),
  Country('SY', 'Syria'),
  Country('TW', 'Taiwan'),
  Country('TJ', 'Tajikistan'),
  Country('TZ', 'Tanzania'),
  Country('TH', 'Thailand'),
  Country('TL', 'Timor-Leste'),
  Country('TG', 'Togo'),
  Country('TK', 'Tokelau'),
  Country('TO', 'Tonga'),
  Country('TT', 'Trinidad & Tobago'),
  Country('TA', 'Tristan da Cunha'),
  Country('TN', 'Tunisia'),
  Country('TR', 'Türkiye'),
  Country('TM', 'Turkmenistan'),
  Country('TC', 'Turks & Caicos Islands'),
  Country('TV', 'Tuvalu'),
  Country('UM', 'U.S. Outlying Islands'),
  Country('VI', 'U.S. Virgin Islands'),
  Country('UG', 'Uganda'),
  Country('UA', 'Ukraine'),
  Country('AE', 'United Arab Emirates'),
  Country('GB', 'United Kingdom'),
  Country('UN', 'United Nations'),
  Country('US', 'United States'),
  Country('UY', 'Uruguay'),
  Country('UZ', 'Uzbekistan'),
  Country('VU', 'Vanuatu'),
  Country('VA', 'Vatican City'),
  Country('VE', 'Venezuela'),
  Country('VN', 'Vietnam'),
  Country('WF', 'Wallis & Futuna'),
  Country('EH', 'Western Sahara'),
  Country('YE', 'Yemen'),
  Country('ZM', 'Zambia'),
  Country('ZW', 'Zimbabwe'),
];
